# Custom Language File for Launcher Customizer

[ejs.app]
title = "Nexus Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "https://x.com/VonDefiant12"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@vondefiant2259"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/VonDefiant/NexusLauncher"
supportLink = "https://github.com/VonDefiant/NexusLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenido a Nexus Launcher"
welcomeDescription = "Este launcher te hara más facil las configuraciones."
welcomeDescCTA = "Diviertete."
